server:
                port: 8081
                spring:
                  datasource:
                    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&characterEncoding=utf8
                    username: root
                    password: 1997326sen
                    driver-class-name: com.mysql.cj.jdbc.Driver
                    type: com.alibaba.druid.pool.DruidDataSource

                  jpa:
                    show-sql: true
                    hibernate:
                      ddl-auto: update